services:
  # Web Service (FastAPI Backend)
  - type: web
    name: agilescribe-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: agilescribe-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://v0-agile-forge-40higfdur-clariq.vercel.app

databases:
  # PostgreSQL Database
  - name: agilescribe-db
    plan: starter
    databaseName: agilescribe
    user: agilescribe_user
