services:
  # Backend API Service
  - type: web
    name: agileforge-api
    env: python
    plan: starter  # Free tier, upgrade to standard for production
    buildCommand: pip install -r requirements-production.txt
    startCommand: python production_backend.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase-config
          property: url
      - key: SUPABASE_SERVICE_KEY
        fromDatabase:
          name: supabase-config
          property: service_key
      - key: FRONTEND_URL
        value: https://your-frontend-domain.vercel.app
      - key: PRODUCTION_DOMAINS
        value: your-frontend-domain.vercel.app,your-custom-domain.com
      - key: ALLOWED_HOST
        value: agileforge-api.onrender.com
    healthCheckPath: /health
    
  # Frontend (if deploying on Render instead of Vercel)
  - type: web
    name: agileforge-frontend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://agileforge-api.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        fromDatabase:
          name: supabase-config
          property: url
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        fromDatabase:
          name: supabase-config
          property: anon_key

databases:
  # Configuration store for Supabase credentials
  - name: supabase-config
    databaseName: config
    user: config_user
