global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # AgileForge Backend API
  - job_name: 'agileforge-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # AgileForge Frontend (if metrics are exposed)
  - job_name: 'agileforge-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/_next/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL metrics (if using local postgres)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health'
    scrape_interval: 10s
    scrape_timeout: 5s 